[package]
name = "cell"
version = "0.1.0"
authors = ["Lucas Ramirez <lucas.ramirez@epfl.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.14"
